- hosts: all
  vars:
    users:
      - name: ivoputzer
        comment: Ivo von Putzer Reibegg
        password: $6$IdVtXdaOmTYWw7xW$jQvaLuYWJobdC/k1dzmY61wyvYF1YLEl4AVzqUxAVVUik5HqflLbgI/ALnRsKBNPfgOzRw03zs742lo9HwYP.1
        state: present
      - name: pcoletta
        comment: Piervito Coletta
        password: $5$7IliVXi8WfrV6cv9$Qh9YwPMApwjhcgyrghSw9RgNwfP4BAZb8k8EkU.Kn.1
        state: present
      - name: fdemontis
        comment: Francesco De Montis
        password: $5$sUzZcwX65tfUXhXf$Z0mM5n3eDX/ykVhgqFQE33.zhB7gl0roa5AlJ9c6D8/
        state: present
      - name: ssocolovschi
        comment: Serghei Socolovschi
        password: $5$yKGGnUNOLRXdtHy/$1mApzYbD7YH1fdoB5.SdgrQrzE68WL38.te2torX5BB
      state: present
  roles:
    - role: users
    - role: docker
