  - name: Clone battleship repo
    ansible.builtin.git:
      repo: https://github.com/ivoputzer/awesome-devops-and-cd-ed4
      dest: /battleship
      force: false

  # - name: install npm dependencies
  #   npm:
  #     path: /battleship

  - name: npm install
    ignore_errors: yes
    ansible.builtin.shell: sudo npm install

  - name: kill node
    ignore_errors: yes
    ansible.builtin.shell: sudo killall node

  - name: npm run dev
    ansible.builtin.command:
      cmd: sudo npm run dev
      chdir: /battleship
    async: 1000
    poll: 0

  - name: npm run start
    ansible.builtin.command:
      cmd: sudo npm run start
      chdir: /battleship
    async: 1000
    poll: 0

