---
- name: install nodejs dependencies
  apt:
    name:
      - apt-transport-https
      - gcc
      - g++
      - make

- name: add nodejs apt key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: add nodejs repository
  apt_repository:
    repo: deb https://deb.nodesource.com/node_16.x {{ ansible_lsb.codename }} main
    state: present
    update_cache: yes

- name: install nodejs
  apt:
    name: nodejs
    state: present

- name: install battleship dependencies
  npm:
    path: /vagrant

# - name: run battleship game
#   command:
#     chdir: /vagrant
#     cmd: npm run start
#   async: 1000
#   poll: 0

# - name: make sure battleship is actually running
#   shell: ps aux | grep node
#   register: app_status

# - debug: msg={{ app_status.stdout_lines }}

# - name: Install mosh
#   apt:
#     state: latest
#     pkg: mosh
